[build-system]
requires = ["setuptools", 
        "wheel"
        ]
build-backend = "setuptools.build_meta"

[project]
name = "msmbuilder-agent"
version = "0.1.0"
requires-python = ">= 3.10"
dependencies = [
  "numpy>=1.26.0",
  "pyyaml>=6.0.3",
  "matplotlib>=3.10.8",
  "mdtraj>=1.11.0",
  "scipy>=1.16.3",
  "openai>=2.21.0",
  "gradio>=6.6.0"
]
readme = "README.md"
authors = [
  {name = "Zige Liu", email = "zliu2262@wisc.edu"},
  {name = "Xinchi Liu", email = "xliu2434@wisc.edu"},
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["msm_agent*"]
exclude = ["images*", "ala2_test_data*"]