[build-system]
requires = ["setuptools", 
        "wheel"
        ]
build-backend = "setuptools.build_meta"

[project]
name = "msmbuilder-agent"
version = "0.1.0"
requires-python = ">= 3.10"
dependencies = [
  "numpy",
  "pyyaml",
  "matplotlib",
  "mdtraj",
  "scipy",
  "openai",
  "gradio"
]
readme = "README.md"
authors = [
  {name = "Zige Liu", email = "zliu2262@wisc.edu"},
  {name = "Xinchi Liu", email = "xliu2434@wisc.edu"},
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["msm_agent*"]
exclude = ["images*", "ala2_test_data*"]